FROM node:lts:alpine as builder

WORKDIR /usr/src/app

COPY package*.json yarn.lock ./

RUN yarn install


COPY . ./

CMD ["yarn", "build"]


FROM nginx:latest
COPY --from=builder /usr/src/app/build /usr/share/nginx/html
COPY nginx/nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx","-g","deamon off;"]